<?php

namespace Kdv\QuizBundle\Repository;

/**
 * SessionAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
