<?php

namespace Proxies\__CG__\Kdv\QuizBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Question extends \Kdv\QuizBundle\Entity\Question implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'id', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'enunciated', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'type', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'picturePath', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'quiz', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'category', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'answers', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'sessionAnswers'];
        }

        return ['__isInitialized__', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'id', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'enunciated', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'type', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'picturePath', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'quiz', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'category', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'answers', '' . "\0" . 'Kdv\\QuizBundle\\Entity\\Question' . "\0" . 'sessionAnswers'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Question $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnunciated($enunciated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnunciated', [$enunciated]);

        return parent::setEnunciated($enunciated);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnunciated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnunciated', []);

        return parent::getEnunciated();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnswer(\Kdv\QuizBundle\Entity\Answer $answer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnswer', [$answer]);

        return parent::addAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnswer(\Kdv\QuizBundle\Entity\Answer $answer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnswer', [$answer]);

        return parent::removeAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswers', []);

        return parent::getAnswers();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuiz(\Kdv\QuizBundle\Entity\Quiz $quiz = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuiz', [$quiz]);

        return parent::setQuiz($quiz);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuiz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuiz', []);

        return parent::getQuiz();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Kdv\QuizBundle\Entity\Category $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addSessionAnswer(\Kdv\QuizBundle\Entity\SessionAnswer $sessionAnswer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSessionAnswer', [$sessionAnswer]);

        return parent::addSessionAnswer($sessionAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSessionAnswer(\Kdv\QuizBundle\Entity\SessionAnswer $sessionAnswer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSessionAnswer', [$sessionAnswer]);

        return parent::removeSessionAnswer($sessionAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessionAnswers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionAnswers', []);

        return parent::getSessionAnswers();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicturePath($picturePath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicturePath', [$picturePath]);

        return parent::setPicturePath($picturePath);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicturePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicturePath', []);

        return parent::getPicturePath();
    }

}
